micronaut:
  server:
    port: 6060
  application:
    name: micronautPayments
datasources:
  default:
    jdbcUrl: ${JDBC_URL:`jdbc:mysql://127.0.0.1:3306/payments`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:pass}
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
jpa:
  default:
    packages-to-scan:
      - 'com.bogdan'
    properties:
      hibernate:
        hbm2ddl:
          auto: update