version: "3.9"
services:
  mysql:
    image: mysql:8.0.23
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    cpus: "0.5"
    mem_limit: 500m
    networks:
      local-net:
        ipv4_address: 10.5.0.2
  ratpack:
    build: ./ratpack-payments/.
    environment:
      - RATPACK_DB_URL=jdbc:mysql://10.5.0.2:3306/payments
    ports:
    - "5050:5050"
    cpus: "0.5"
    mem_limit: 500m
    networks:
      local-net:
        ipv4_address: 10.5.0.3
    depends_on:
      - mysql

networks:
  local-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16