version: "3.9"
services:
  mysql:
    image: mysql:8.0.23
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
    - ./volumes/mysql:/var/lib/mysql
    cpus: "0.5"
    mem_limit: 500m
  ratpack:
    build: ./ratpack-payments/.
    ports:
    - "5050:5050"
    cpus: "0.5"
    mem_limit: 500m