version: "3.9"

networks:
  local-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16

services:
  mysql:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: payments
    cpus: "0.5"
    mem_limit: 500m
    networks:
      - local-net
  ratpack:
    build: ./ratpack-payments/.
    environment:
      JDBC_URL: jdbc:mysql://mysql:3306/payments
      RATPACK_DB_URL: jdbc:mysql://mysql:3306/payments
    ports:
      - "5050:5050"
    cpus: "0.5"
    mem_limit: 500m
    networks:
      - local-net
    depends_on:
      - mysql
  prometheus:
    image: prom/prometheus:v2.24.1
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    cpus: "0.5"
    mem_limit: 2000m
    networks:
      - local-net
    restart: always
  node-exporter:
    image: prom/node-exporter:v1.1.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    cpus: "0.1"
    mem_limit: 50m
    networks:
      - local-net
    restart: always
    deploy:
      mode: global
  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - 9093:9093
    volumes:
      - ./monitoring/alertmanager/:/etc/alertmanager/
    cpus: "0.1"
    mem_limit: 200m
    networks:
      - local-net
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
  grafana:
    image: grafana/grafana:7.4.1
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: admin
    volumes:
      - ./monitoring/grafana/config:/etc/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    cpus: "0.1"
    mem_limit: 200m
    networks:
      - local-net
    restart: always