{
 "title": "Ratpack Application Metrics",
 "tags": [
  "prometheus",
  "micrometer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "application", "query": "ratpack" },
   {
    "name": "version",
    "query": {
     "query": "label_values(system_cpu_count{app=~\"$application\"}, appVersion)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "brand" },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"$application\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "$version" }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_response_time_seconds_bucket{app=~\"$application\", appVersion=~\"$version\"}[$__range])) by (le))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Api Error Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_status_count_beans_total{app=~\"$application\", appVersion=~\"$version\", response!~\"^(20|30).*\"}[$__range])) / \nsum(rate(http_server_response_status_count_beans_total{app=~\"$application\", appVersion=~\"$version\"}[$__range]))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{job=~\"$application\"}) / \nsum(system_cpu_count{job=~\"$application\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$application\"}) / \nsum(jvm_memory_max_bytes{job=~\"$application\"})",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$application\", area=\"heap\"}) / \nsum(jvm_memory_max_bytes{job=~\"$application\", area=\"heap\"})",
     "legendFormat": "Heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$application\", area=\"nonheap\"}) / \nsum(jvm_memory_max_bytes{job=~\"$application\", area=\"nonheap\"})",
     "legendFormat": "Non Heap"
    }
   ]
  },
  { "title": "Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_response_time_seconds_bucket{app=~\"$application\", appVersion=~\"$version\"}[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "sum(rate(http_server_response_time_seconds_sum{app=~\"$application\", appVersion=~\"$version\"}[5m])) by (method, path) / \nsum(rate(http_server_response_time_seconds_count{app=~\"$application\", appVersion=~\"$version\"}[5m])) by (method, path)",
     "legendFormat": "{{method}}::{{path}}"
    }
   ]
  },
  {
   "title": "Api Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_response_status_count_beans_total{app=~\"$application\", appVersion=~\"$version\"}[5m]))",
     "legendFormat": "requests/$__interval"
    }
   ]
  },
  {
   "title": "Requests by Path",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_status_count_beans_total{app=~\"$application\", appVersion=~\"$version\"}[5m])) by (method, path)",
     "legendFormat": "{{method}}::{{path}}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_response_status_count_beans_total{app=~\"$application\", appVersion=~\"$version\"}[5m])) by (response)",
     "legendFormat": "{{response}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(system_cpu_usage{job=~\"$application\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(system_cpu_count{job=~\"$application\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$application\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=~\"$application\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$application\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=~\"$application\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=~\"$application\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM NonHeap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$application\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=~\"$application\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=~\"$application\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  }
 ]
}