/*
 * This file is generated by jOOQ.
 */
package com.bogdan.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private String  title;

    public Employee() {}

    public Employee(Employee value) {
        this.id = value.id;
        this.name = value.name;
        this.title = value.title;
    }

    public Employee(
        Integer id,
        String  name,
        String  title
    ) {
        this.id = id;
        this.name = name;
        this.title = title;
    }

    /**
     * Getter for <code>payments.employee.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>payments.employee.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>payments.employee.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>payments.employee.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>payments.employee.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>payments.employee.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employee (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(title);

        sb.append(")");
        return sb.toString();
    }
}
