/*
 * This file is generated by jOOQ.
 */
package com.bogdan.jooq;


import com.bogdan.jooq.tables.Employee;
import com.bogdan.jooq.tables.HibernateSequence;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payments extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>payments</code>
     */
    public static final Payments PAYMENTS = new Payments();

    /**
     * The table <code>payments.employee</code>.
     */
    public final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>payments.hibernate_sequence</code>.
     */
    public final HibernateSequence HIBERNATE_SEQUENCE = HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * No further instances allowed
     */
    private Payments() {
        super("payments", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Employee.EMPLOYEE,
            HibernateSequence.HIBERNATE_SEQUENCE);
    }
}
