/*
 * This file is generated by jOOQ.
 */
package com.bogdan.jooq;


import com.bogdan.jooq.routines.Insertrand;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in payments.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>payments.InsertRand</code>
     */
    public static void insertrand(
          Configuration configuration
        , Integer numrows
    ) {
        Insertrand p = new Insertrand();
        p.setNumrows(numrows);

        p.execute(configuration);
    }
}
