/*
 * This file is generated by jOOQ.
 */
package com.bogdan.jooq;


import com.bogdan.jooq.tables.Employee;
import com.bogdan.jooq.tables.HibernateSequence;


/**
 * Convenience access to all tables in payments.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>payments.employee</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>payments.hibernate_sequence</code>.
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = HibernateSequence.HIBERNATE_SEQUENCE;
}
