global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: 'payments'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'ratpack'
    dns_sd_configs:
      - names:
          - 'tasks.ratpack'
        type: 'A'
        port: 5050
    metrics_path: /api/metrics/prometheus
    static_configs:
      - targets: [ 'ratpack:5050' ]